name: my_fit_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  get_it: ^8.0.3

  freezed: ^2.5.7
  go_router: ^14.6.2
  firebase_auth: ^5.3.4
  firebase_core: ^3.9.0
  cloud_firestore: ^5.6.0
  flutter_riverpod: ^2.6.1
  firebase_storage: ^12.3.7
  riverpod_annotation: ^2.6.1
  flutter_native_splash: ^2.4.3
  flutter_dotenv: ^5.2.1
  curved_labeled_navigation_bar: ^2.0.5
  freezed_annotation: ^2.4.4
  image_picker_loading_jm: ^0.0.10

  my_fit_ui_kit:
    git:
      url: https://github.com/JEISONVARGAS1/my_fit_ui_kit.git


  cupertino_icons: ^1.0.8

dev_dependencies:
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.3

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/


  fonts:
    - family: bebas_neue
      fonts:
        - asset: assets/fonts/Bebas_Neue/BebasNeue-Regular.ttf

    - family: istok_web
      fonts:
        - asset: assets/fonts/Istok_Web/IstokWeb-Bold.ttf
        - asset: assets/fonts/Istok_Web/IstokWeb-BoldItalic.ttf
        - asset: assets/fonts/Istok_Web/IstokWeb-Italic.ttf
        - asset: assets/fonts/Istok_Web/IstokWeb-Regular.ttf



